KUSITMS-MeetUp-2/27th_Meetup_T2_service_back

build.gradle
src/main/java/com/modagbul/BE/global/config/querydsl/QuerydslConfig.java

QuerydslConfig 추가
QuerydslConfig, 의존성 추가

feat: QuerydslConfig 추가

---

build.gradle
src/main/java/com/modagbul/BE/domain/user/entity/User.java
src/main/java/com/modagbul/BE/domain/user/exception/UserException.java
src/main/java/com/modagbul/BE/global/config/security/SecurityConfig.java
src/main/java/com/modagbul/BE/global/config/security/exception/LoggedInUserNotFoundException.java
src/main/java/com/modagbul/BE/global/config/security/exception/NoAuthenticationFoundException.java
src/main/java/com/modagbul/BE/global/config/security/exception/SecurityException.java
src/main/java/com/modagbul/BE/global/config/security/exception/UserNotAuthenticatedWithOAuth2Exception.java
src/main/java/com/modagbul/BE/global/config/security/util/SecurityUtils.java
src/main/java/com/modagbul/BE/global/exception/ApplicationException.java
src/main/java/com/modagbul/BE/global/exception/GlobalExceptionHandler.java

SecurityConfig 및 에러 처리 추가
SecurityConfig 추가, 이 과정에서 생기는 에러 처리 추가

feat: SecurityConfig 추가

---

build.gradle
src/main/java/com/modagbul/BE/global/config/jwt/JwtAccessDeniedHandler.java
src/main/java/com/modagbul/BE/global/config/jwt/JwtAuthenticationEntryPoint.java
src/main/java/com/modagbul/BE/global/config/jwt/JwtFilter.java
src/main/java/com/modagbul/BE/global/config/jwt/JwtSecurityConfig.java
src/main/java/com/modagbul/BE/global/config/jwt/TokenProvider.java
src/main/java/com/modagbul/BE/global/config/jwt/constants/JwtConstants.java
src/main/java/com/modagbul/BE/global/config/jwt/exception/ExpiredException.java
src/main/java/com/modagbul/BE/global/config/jwt/exception/IllegalException.java
src/main/java/com/modagbul/BE/global/config/jwt/exception/JwtException.java
src/main/java/com/modagbul/BE/global/config/jwt/exception/MalformedException.java
src/main/java/com/modagbul/BE/global/config/jwt/exception/UnknownException.java
src/main/java/com/modagbul/BE/global/config/jwt/exception/UnsupportedException.java
src/main/java/com/modagbul/BE/global/config/security/SecurityConfig.java
src/main/java/com/modagbul/BE/global/config/security/constants/SecurityConstants.java
src/main/java/com/modagbul/BE/global/config/security/exception/LoggedInUserNotFoundException.java
src/main/java/com/modagbul/BE/global/config/security/exception/NoAuthenticationFoundException.java
src/main/java/com/modagbul/BE/global/config/security/exception/UserNotAuthenticatedWithOAuth2Exception.java
src/main/java/com/modagbul/BE/global/dto/TokenInfoResponse.java
src/main/java/com/modagbul/BE/global/exception/GlobalExceptionHandler.java

jwt 설정 추가
- JwtFilter, TokenProvider, JwtAccessDeniedHandler 등 jwt 관련 설정 추가
- 이에 대한 에러 처리 추가

feat: jwt 설정 추가

---

build.gradle
src/main/java/com/modagbul/BE/fcm/config/FcmConfig.java
src/main/java/com/modagbul/BE/fcm/constants/FcmConstants.java
src/main/java/com/modagbul/BE/fcm/controller/FcmController.java
src/main/java/com/modagbul/BE/fcm/dto/FcmDto.java
src/main/java/com/modagbul/BE/fcm/exception/FirebaseException.java
src/main/java/com/modagbul/BE/fcm/exception/InitializeException.java
src/main/java/com/modagbul/BE/fcm/exception/NotificationException.java
src/main/java/com/modagbul/BE/fcm/service/FcmService.java

feat : fcm 설정 추가

---

build.gradle
src/main/java/com/modagbul/BE/fcm/config/FcmConfig.java
src/main/java/com/modagbul/BE/fcm/constants/FcmConstants.java
src/main/java/com/modagbul/BE/fcm/controller/FcmController.java
src/main/java/com/modagbul/BE/fcm/dto/FcmDto.java
src/main/java/com/modagbul/BE/fcm/exception/MessagingException.java
src/main/java/com/modagbul/BE/fcm/exception/NotificationException.java
src/main/java/com/modagbul/BE/fcm/service/FcmService.java
src/main/java/com/modagbul/BE/fcm/service/FcmServiceImpl.java
src/main/java/com/modagbul/BE/global/config/security/SecurityConfig.java

fcm 여러 기기 메시지 전송 추가
sendMultipleDevices 서비스 단 추가 api 추가

feat : fcm 여러 기기에 메시지 전송 추가

---

build.gradle
src/main/java/com/modagbul/BE/fcm/constants/FcmConstants.java
src/main/java/com/modagbul/BE/fcm/controller/FcmController.java
src/main/java/com/modagbul/BE/fcm/dto/FcmDto.java
src/main/java/com/modagbul/BE/fcm/service/FcmService.java
src/main/java/com/modagbul/BE/fcm/service/FcmServiceImpl.java
src/main/java/com/modagbul/BE/global/exception/GlobalExceptionHandler.java

fcm 제주 관련 설정 추가
주제로 전송하기 api 및 서비스 구현
- And/or연산 일괄 처리하는 경우
- 조금 더 복잡한 조건절 연산인 경우
https://github.com/KUSITMS-MeetUp-2/27th_Meetup_T2_service_back/issues/22#issue-1672226412

feat : fcm 주제 관련 설정 추가

---

src/main/java/com/modagbul/BE/fcm/config/FcmConfig.java

오류 수정
InputStream serviceAccount = getClass().getResourceAsStream(firebaseConfigPath);

fix : 오류 수정

---

src/main/java/com/modagbul/BE/fcm/config/FcmConfig.java

fix : logs 보기

---

src/main/java/com/modagbul/BE/BeApplication.java
src/main/java/com/modagbul/BE/domain/team/constant/TeamConstant.java
src/main/java/com/modagbul/BE/domain/team/controller/TeamController.java
src/main/java/com/modagbul/BE/domain/team/dto/TeamDto.java
src/main/java/com/modagbul/BE/domain/team/dto/TeamMapper.java
src/main/java/com/modagbul/BE/domain/team/entity/Team.java
src/main/java/com/modagbul/BE/domain/team/repository/TeamRepository.java
src/main/java/com/modagbul/BE/domain/team/service/InvitationCodeGenerator.java
src/main/java/com/modagbul/BE/domain/team/service/TeamService.java
src/main/java/com/modagbul/BE/domain/team/service/TeamServiceImpl.java
src/main/java/com/modagbul/BE/domain/teammember/entity/TeamMember.java
src/main/java/com/modagbul/BE/domain/teammember/repository/TeamMemberRepository.java
src/main/java/com/modagbul/BE/domain/user/entity/User.java
src/main/java/com/modagbul/BE/domain/user/repository/UserRepository.java
src/main/java/com/modagbul/BE/domain/user/repository/UserRepositoryCustom.java
src/main/java/com/modagbul/BE/domain/user/repository/UserRepositoryCustomImpl.java
src/main/java/com/modagbul/BE/domain/user/service/UserServiceImpl.java
src/main/java/com/modagbul/BE/fcm/constant/FcmConstant.java
src/main/java/com/modagbul/BE/fcm/controller/FcmController.java
src/main/java/com/modagbul/BE/fcm/exception/InitializeException.java
src/main/java/com/modagbul/BE/fcm/exception/MessagingException.java
src/main/java/com/modagbul/BE/fcm/exception/NotificationException.java
src/main/java/com/modagbul/BE/global/annotation/Enum.java
src/main/java/com/modagbul/BE/global/annotation/EnumValidator.java
src/main/java/com/modagbul/BE/global/config/jwt/JwtAuthenticationEntryPoint.java
src/main/java/com/modagbul/BE/global/config/security/SecurityConfig.java
src/main/java/com/modagbul/BE/global/entity/BaseTimeEntity.java
src/main/java/com/modagbul/BE/global/exception/GlobalExceptionHandler.java
src/main/java/com/modagbul/BE/test/controller/TestController.java
src/main/java/com/modagbul/BE/test/service/TestService.java

소모임 생성 및 참여코드 만들기
- 소모임 생성하기
- 참여코드 만들기
- 소모임 생성할 때 소모임-멤버에 추가
https://github.com/KUSITMS-MeetUp-2/27th_Meetup_T2_service_back/issues/39#issue-1689328888

feat/createTeam : 소모임 생성 및 참여코드 만들기

---

src/main/java/com/modagbul/BE/domain/team/constant/TeamConstant.java
src/main/java/com/modagbul/BE/domain/team/controller/TeamController.java
src/main/java/com/modagbul/BE/domain/team/dto/TeamDto.java
src/main/java/com/modagbul/BE/domain/team/entity/Team.java
src/main/java/com/modagbul/BE/domain/team/exception/AlreadyJoinException.java
src/main/java/com/modagbul/BE/domain/team/exception/AuthenticationException.java
src/main/java/com/modagbul/BE/domain/team/exception/TeamException.java
src/main/java/com/modagbul/BE/domain/team/repository/TeamRepository.java
src/main/java/com/modagbul/BE/domain/team/service/TeamService.java
src/main/java/com/modagbul/BE/domain/team/service/TeamServiceImpl.java
src/main/java/com/modagbul/BE/domain/teammember/entity/TeamMember.java
src/main/java/com/modagbul/BE/domain/teammember/repository/TeamMemberRepository.java
src/main/java/com/modagbul/BE/domain/user/controller/UserController.java
src/main/java/com/modagbul/BE/domain/user/entity/User.java
src/main/java/com/modagbul/BE/domain/user/service/UserServiceImpl.java

소모임 초대코드 인증 및 소모임 참여
- 소모임 초대코드 인증
- 소모임 참여
- team: team_member은 1: n 양방향 연관관계, user: team_member은 1:n 단방향 연관관계
https://github.com/KUSITMS-MeetUp-2/27th_Meetup_T2_service_back/issues/41#issue-1689539966

feat/authcode: 소모임 초대코드 인증 및 소모임 참여

---

src/main/java/com/modagbul/BE/domain/team/controller/TeamController.java
src/main/java/com/modagbul/BE/domain/team/dto/TeamDto.java
src/main/java/com/modagbul/BE/domain/team/service/TeamService.java
src/main/java/com/modagbul/BE/domain/team/service/TeamServiceImpl.java

초대코드 인증 응답코드 수정
초대코드 인증하는 부분 응답 객체에서 data 부분 없었음-> teamId 반환 수정

fix/authcode: auth 응답 객체 수정

---

src/main/java/com/modagbul/BE/domain/team/constant/TeamConstant.java
src/main/java/com/modagbul/BE/domain/team/controller/TeamController.java
src/main/java/com/modagbul/BE/domain/team/dto/TeamDto.java
src/main/java/com/modagbul/BE/domain/team/dto/TeamMapper.java
src/main/java/com/modagbul/BE/domain/team/entity/Team.java
src/main/java/com/modagbul/BE/domain/team/exception/AccessException.java
src/main/java/com/modagbul/BE/domain/team/exception/NotHavaTeamIdException.java
src/main/java/com/modagbul/BE/domain/team/repository/TeamRepository.java
src/main/java/com/modagbul/BE/domain/team/repository/TeamRepositoryCustom.java
src/main/java/com/modagbul/BE/domain/team/repository/TeamRepositoryCustomImpl.java
src/main/java/com/modagbul/BE/domain/team/service/TeamService.java
src/main/java/com/modagbul/BE/domain/team/service/TeamServiceImpl.java
src/main/java/com/modagbul/BE/global/config/jwt/ExceptionHandlerFilter.java
src/main/java/com/modagbul/BE/global/config/jwt/JwtAuthenticationEntryPoint.java
src/main/java/com/modagbul/BE/global/config/jwt/JwtFilter.java
src/main/java/com/modagbul/BE/global/config/jwt/JwtSecurityConfig.java
src/main/java/com/modagbul/BE/global/config/jwt/TokenProvider.java
src/main/java/com/modagbul/BE/global/config/security/SecurityConfig.java
src/main/java/com/modagbul/BE/global/exception/GlobalExceptionHandler.java

소모임 수정하기 및 소모임 수정하기 위한 정보 조회 (모두 소모임장만 권한 있음)
소모임 수정하기 
소모임 수정하기 위한 정보 조회
#47

feat/goalboard_updateteam: 소모임 수정하기 (소모임장)

---

src/main/java/com/modagbul/BE/domain/mission/Exception/MissionAuthDeniedException.java
src/main/java/com/modagbul/BE/domain/mission/Exception/MissionException.java
src/main/java/com/modagbul/BE/domain/mission/Exception/NotFoundMissionException.java
src/main/java/com/modagbul/BE/domain/mission/constant/MissionConstant.java
src/main/java/com/modagbul/BE/domain/mission/controller/MissionController.java
src/main/java/com/modagbul/BE/domain/mission/dto/MissionDto.java
src/main/java/com/modagbul/BE/domain/mission/dto/MissionMapper.java
src/main/java/com/modagbul/BE/domain/mission/entity/Mission.java
src/main/java/com/modagbul/BE/domain/mission/repository/MissionRepository.java
src/main/java/com/modagbul/BE/domain/mission/service/MissionService.java

- 소모임장 권한으로 미션 생성 및 수정.
- 아직 login한 userId를 얻지 못해 일단 loginId = 1L로 지정

Feat/mission 소모임장 권한 미션 생성 및 수정

---

src/main/java/com/modagbul/BE/domain/notice/constant/NoticeConstant.java
src/main/java/com/modagbul/BE/domain/notice/controller/NoticeController.java
src/main/java/com/modagbul/BE/domain/notice/dto/NoticeDto.java
src/main/java/com/modagbul/BE/domain/notice/dto/NoticeMapper.java
src/main/java/com/modagbul/BE/domain/notice/entity/Notice.java
src/main/java/com/modagbul/BE/domain/notice/repository/NoticeRepository.java
src/main/java/com/modagbul/BE/domain/notice/service/NoticeService.java
src/main/java/com/modagbul/BE/domain/notice/service/NoticeServiceImpl.java
src/main/java/com/modagbul/BE/domain/noticeread/entity/NoticeRead.java
src/main/java/com/modagbul/BE/domain/noticeread/repository/NoticeReadRepository.java
src/main/java/com/modagbul/BE/domain/team/entity/Team.java
src/main/java/com/modagbul/BE/domain/teammember/repository/TeamMemberRepository.java
src/main/java/com/modagbul/BE/test/controller/TestController.java
src/main/java/com/modagbul/BE/test/service/TestService.java
src/test/java/com/modagbul/BE/domain/user/service/UserServiceImplTest.java

공지사항 생성하기
공지사항 생성하면 읽음처리 테이블도 자동으로 생성하기 
#55

Feat/createNotice: 공지사항 생성하기

---

src/main/java/com/modagbul/BE/domain/mission/service/MissionService.java

fix : 로그인한 유저 계정

---

src/main/java/com/modagbul/BE/domain/notice/board/constant/NoticeConstant.java
src/main/java/com/modagbul/BE/domain/notice/board/controller/NoticeController.java
src/main/java/com/modagbul/BE/domain/notice/board/dto/NoticeDto.java
src/main/java/com/modagbul/BE/domain/notice/board/repository/NoticeRepositoryCustom.java
src/main/java/com/modagbul/BE/domain/notice/board/repository/NoticeRepositoryCustomImpl.java
src/main/java/com/modagbul/BE/domain/notice/board/service/NoticeService.java
src/main/java/com/modagbul/BE/domain/notice/board/service/NoticeServiceImpl.java

공지 전체 조회
- 공지 전체 조회 , 정렬 순 : 1. 안 읽은 것 2. 날짜
- 공지 안 읽은 것만 조회 , 정렬 순 : 날짜
#90

feat: 공지 전체 조회, 안 읽은 것만 조회

---

src/main/java/com/modagbul/BE/domain/usermission/service/UserMissionService.java

fix : 인증사진 정렬 규칙 - 본인 사진 맨 앞 정렬 #96

---

src/main/java/com/modagbul/BE/domain/team/constant/TeamConstant.java
src/main/java/com/modagbul/BE/domain/team/controller/TeamController.java
src/main/java/com/modagbul/BE/domain/team/dto/TeamDto.java
src/main/java/com/modagbul/BE/domain/team/repository/TeamRepositoryCustom.java
src/main/java/com/modagbul/BE/domain/team/repository/TeamRepositoryCustomImpl.java
src/main/java/com/modagbul/BE/domain/team/service/TeamService.java
src/main/java/com/modagbul/BE/domain/team/service/TeamServiceImpl.java

홈 화며에서 소모임 정보 보기 
홈 화면에서 소모임 정보를 봅니다
#99

feat: 홈 화면에서 소모임 정보 보기

---

src/main/java/com/modagbul/BE/domain/mission/controller/MissionController.java

fix : 미션 생성 url 변경

---

src/main/java/com/modagbul/BE/domain/user/entity/User.java

feat : User Entity token, 알림설정 column 추가

---

src/main/java/com/modagbul/BE/domain/user/constant/UserConstant.java
src/main/java/com/modagbul/BE/domain/user/controller/UserController.java
src/main/java/com/modagbul/BE/domain/user/dto/UserDto.java
src/main/java/com/modagbul/BE/domain/user/entity/User.java
src/main/java/com/modagbul/BE/domain/user/service/UserService.java
src/main/java/com/modagbul/BE/domain/user/service/UserServiceImpl.java

feat : 알림설정 공지/리마인드/불던지기 기능 추가

---

src/main/java/com/modagbul/BE/domain/user/service/UserServiceImpl.java

fix : mypage 참여한 소모임 리스트

---

build.gradle
src/main/java/com/modagbul/BE/domain/user/service/Kakao.java
src/main/java/com/modagbul/BE/domain/user/service/UserService.java
src/main/java/com/modagbul/BE/domain/user/service/UserServiceImpl.java
src/test/java/com/modagbul/BE/common/factory/UserFactory.java
src/test/java/com/modagbul/BE/domain/user/service/UserServiceImplTest.java

사용자 로그인 테스트 코드 작성
- saveUser()메소드 저장 테스트 코드 
- login()메소드 테스트 코드
- signup()메소드 테스트 코드 
- 테스트코드를 작성하기 위해 리팩토링
- 전체적으로 테스트 코드를 작성하기 어렵게 짬 -> 작성하기 쉽도록 계속 리팩토링을 해야 함

test: 사용자 로그인 테스트

---

src/main/java/com/modagbul/BE/domain/team/constant/TeamConstant.java
src/main/java/com/modagbul/BE/domain/team/controller/TeamController.java
src/main/java/com/modagbul/BE/domain/team/dto/TeamDto.java
src/main/java/com/modagbul/BE/domain/team/service/TeamService.java
src/main/java/com/modagbul/BE/domain/team/service/TeamServiceImpl.java
src/main/java/com/modagbul/BE/domain/user/dto/UserDto.java
src/main/java/com/modagbul/BE/domain/user/entity/User.java
src/main/java/com/modagbul/BE/domain/user/service/UserServiceImpl.java
src/test/java/com/modagbul/BE/common/factory/UserFactory.java
src/test/java/com/modagbul/BE/domain/user/service/UserServiceImplTest.java

- 목표보드 프로필 조회
- 추가정보 입력시 fcm 등록토큰도 입력받을 수 있도록 dto 수정
- 목표보드 프로필 조회
#117

Feat/goalboard profile : 목표보드 프로필 조회

---

src/main/java/com/modagbul/BE/domain/notice/board/service/NoticeServiceImpl.java
src/main/java/com/modagbul/BE/domain/user/controller/UserController.java
src/main/java/com/modagbul/BE/domain/user/dto/UserDto.java
src/main/java/com/modagbul/BE/domain/user/entity/User.java
src/main/java/com/modagbul/BE/domain/user/service/UserService.java
src/main/java/com/modagbul/BE/domain/user/service/UserServiceImpl.java
src/main/java/com/modagbul/BE/fcm/constant/FcmConstant.java

신규 공지 업로드 알림 
- fcm이용해서 신규 공지 업로드 알림
- user엔티티 isNoticePush->isNewUploadPush로 바꿈 (신규 알림이 공지, 투표, 미션 모두 있음)
#105

Feat/fcm notice : 신규 공지 업로드 알림

---

src/main/java/com/modagbul/BE/domain/vote/board/service/VoteServiceImpl.java

- fcm 신규 투표 업로드 알림
- 투표를 새로 업로드 할 시 알림가게 함
#123

feat: fcm 신규 투표 업로드 알림

---

src/test/java/com/modagbul/BE/common/factory/TeamFactory.java
src/test/java/com/modagbul/BE/domain/team/service/TeamServiceImplTest.java
src/test/java/com/modagbul/BE/domain/user/service/UserServiceImplTest.java

닉네임 중복검사 테스트 코드 작성
- 닉네임 중복검사 테스트 코드 작성
- UserServiceImplTest 구조 변화

Test: 닉네임 중복검사 테스트

---

src/main/java/com/modagbul/BE/domain/fire/constant/FireFcmMessage.java
src/main/java/com/modagbul/BE/domain/fire/service/FireService.java

- 불던질 때 푸시 알림 
- 현재 user에 fcmToken 없기에 주석 처리 해놓음

feat : 불던지기 푸시 알림 기능

---

src/main/java/com/modagbul/BE/domain/vote/board/controller/VoteController.java
src/main/java/com/modagbul/BE/domain/vote/board/service/VoteService.java
src/main/java/com/modagbul/BE/domain/vote/board/service/VoteServiceImpl.java
src/main/java/com/modagbul/BE/global/config/jwt/TokenProvider.java

투표하기 API에서 투표 결과 보이도록 수정 
- 투표하기에서 기존에는 투표 결과 안보였는데 투표 결과 보이도록 수정 (프론트 요청)
- JWT 토큰 시간 수정

FIx: 투표하기 API 응답 DTO 수정

---

src/main/java/com/modagbul/BE/domain/vote/board/dto/VoteDto.java
src/main/java/com/modagbul/BE/domain/vote/board/repository/VoteRepositoryCustomImpl.java

투표 결과 DTO 수정
투표 결과에 익명, 복수 투표 여부 보여주기

fix: 투표 결과 DTO 수정

---

src/main/java/com/modagbul/BE/domain/notice/comment/repsitory/NoticeCommentRepositoryCustomImpl.java
src/main/java/com/modagbul/BE/domain/vote/comment/repository/VoteCommentRepositoryCustomImpl.java

comment 조회 순서 변경
comment 목록을 조회할 때는 오래된 순

fix: comment 조회 순서 변경

---

src/main/java/com/modagbul/BE/domain/user/constant/UserConstant.java
src/main/java/com/modagbul/BE/domain/user/controller/UserController.java
src/main/java/com/modagbul/BE/domain/user/dto/UserDto.java
src/main/java/com/modagbul/BE/domain/user/service/UserService.java
src/main/java/com/modagbul/BE/domain/user/service/UserServiceImpl.java
src/main/java/com/modagbul/BE/global/config/redis/repository/RefreshTokenRepository.java
src/main/java/com/modagbul/BE/global/config/security/SecurityConfig.java

추가정보입력여부검사 , 로그아웃 API 추가
- 추가정보입력여부검사 API
- 로그아웃 API
- 로그아웃, 회원탈퇴시 Redis의 리프레시 토큰 삭제

Feat: 추가정보입력여부검사 , 로그아웃 API 추가

---

src/main/java/com/modagbul/BE/domain/user/controller/UserController.java
src/main/java/com/modagbul/BE/domain/user/entity/User.java
src/main/java/com/modagbul/BE/domain/user/service/UserService.java
src/main/java/com/modagbul/BE/domain/user/service/UserServiceImpl.java

feat : 마이페이지 이미지 수정 api

---

src/main/java/com/modagbul/BE/domain/usermission/dto/UserMissionStatusDto.java
src/main/java/com/modagbul/BE/domain/usermission/service/UserMissionService.java

fix : 미션 인증 현황 mystatus 추가

---

src/main/java/com/modagbul/BE/domain/user/dto/UserDto.java
src/main/java/com/modagbul/BE/domain/user/service/UserServiceImpl.java

fix : 마이페이지 리턴값 프로필 이미지 추가

---

src/main/java/com/modagbul/BE/domain/mission/service/MissionBoardService.java

fix : 미션 없을 때 비율 계산 예외처리

---

src/main/java/com/modagbul/BE/domain/mission/controller/MissionController.java
src/main/java/com/modagbul/BE/domain/mission/dto/MissionDetailDto.java
src/main/java/com/modagbul/BE/domain/mission/service/MissionService.java
src/main/java/com/modagbul/BE/domain/usermission/dto/UserMissionDetailDto.java
src/main/java/com/modagbul/BE/domain/usermission/repository/UserMissionRepository.java

fix : usermission list return add achieve img

---

src/main/java/com/modagbul/BE/domain/team/dto/TeamDto.java
src/main/java/com/modagbul/BE/domain/team/service/info/TeamInfoServiceImpl.java

소모임 전체 보기 DTO 수정
소모임 전체 보기에서 유저 닉네임 dto에 추가

fix: 소모임 전체 보기 DTO 수정

---

src/main/java/com/modagbul/BE/domain/mission/constant/MissionBoardFireMessage.java
src/main/java/com/modagbul/BE/domain/mission/controller/MissionController.java
src/main/java/com/modagbul/BE/domain/mission/dto/MissionBoardDto.java
src/main/java/com/modagbul/BE/domain/mission/repository/MissionRepository.java
src/main/java/com/modagbul/BE/domain/mission/service/MissionBoardService.java

feat : 불꽃별 카피라이트 추가

---

src/main/java/com/modagbul/BE/domain/user/service/mypage/UserMyPageServiceImpl.java
src/main/java/com/modagbul/BE/domain/vote/board/dto/VoteDto.java
src/main/java/com/modagbul/BE/domain/vote/board/dto/VoteMapper.java
src/main/java/com/modagbul/BE/domain/vote/board/exception/NotVoteWriterException.java
src/main/java/com/modagbul/BE/domain/vote/board/service/VoteServiceImpl.java

Vote 익명, 복수 여부 처리 수정, 에러 처리 수정
- 익명, 복수처리가 수정이 안되는 오류가 발견->DTO에서 boolean->Boolean으로 수정해서 해결
- VoteServiceImpl에서 해당 투표를 작성한 사람이 아니면 VoteWirterException()이 아니라 NoticeWirterException()을 날려줬음 해당 부분 수정

Fix: Vote 익명, 복수 여부 처리

---

src/main/java/com/modagbul/BE/global/config/security/SecurityConfig.java

SpringSecurityConfig 오타 수정
"/api/v1/users/additional-info" 부분 오타 수정

hotfix: 스프링시큐리티 오타 수정

---

src/main/java/com/modagbul/BE/domain/usermission/dto/UserMissionStatusDto.java
src/main/java/com/modagbul/BE/domain/usermission/service/UserMissionService.java

유저 미션 리스트 로그인한 사용자가 완료,미완료 앞에 오도록

fix : usermission list login user append

---

src/main/java/com/modagbul/BE/domain/notice/board/service/alarm/NoticeAlarmServiceImpl.java
src/main/java/com/modagbul/BE/domain/team_member/service/TeamMemberService.java
src/main/java/com/modagbul/BE/domain/team_member/service/TeamMemberServiceImpl.java
src/main/java/com/modagbul/BE/domain/vote/board/controller/VoteController.java
src/main/java/com/modagbul/BE/domain/vote/board/controller/create/VoteCreationController.java
src/main/java/com/modagbul/BE/domain/vote/board/controller/info/VoteInfoController.java
src/main/java/com/modagbul/BE/domain/vote/board/controller/manage/VoteManagementController.java
src/main/java/com/modagbul/BE/domain/vote/board/repository/VoteRepositoryCustomImpl.java
src/main/java/com/modagbul/BE/domain/vote/board/service/VoteService.java
src/main/java/com/modagbul/BE/domain/vote/board/service/VoteServiceImpl.java
src/main/java/com/modagbul/BE/domain/vote/board/service/alarm/VoteAlarmService.java
src/main/java/com/modagbul/BE/domain/vote/board/service/alarm/VoteAlarmServiceImpl.java
src/main/java/com/modagbul/BE/domain/vote/board/service/create/VoteCreationService.java
src/main/java/com/modagbul/BE/domain/vote/board/service/create/VoteCreationServiceImpl.java
src/main/java/com/modagbul/BE/domain/vote/board/service/info/VoteInfoService.java
src/main/java/com/modagbul/BE/domain/vote/board/service/info/VoteInfoServiceImpl.java
src/main/java/com/modagbul/BE/domain/vote/board/service/manage/VoteManagementService.java
src/main/java/com/modagbul/BE/domain/vote/board/service/manage/VoteManagementServiceImpl.java
src/main/java/com/modagbul/BE/domain/vote/board/service/validate/VoteValidationService.java
src/main/java/com/modagbul/BE/domain/vote/board/service/validate/VoteValidationServiceImpl.java
src/main/java/com/modagbul/BE/domain/vote/comment/dto/VoteCommentMapper.java
src/main/java/com/modagbul/BE/domain/vote/comment/service/VoteCommentServiceImpl.java
src/main/java/com/modagbul/BE/domain/vote/content/service/VoteContentService.java
src/main/java/com/modagbul/BE/domain/vote/content/service/VoteContentServiceImpl.java
src/main/java/com/modagbul/BE/domain/vote/read/service/VoteReadService.java
src/main/java/com/modagbul/BE/domain/vote/read/service/VoteReadServiceImpl.java

투표 신규 생성, 공지 신규 생성 로직 변경 및 리팩토링
- 공지 신규 생성, 투표 신규 생성시 나를 제외한 소모임원에게 알림이 갈 수 있도록 변경
- VoteService, VoteController 단일책임의 원칙을 이용해 리팩토링

fix: 투표 신규 생성, 공지 신규 생성 fcm 알림 로직 변경 및 리팩토링

---

src/main/java/com/modagbul/BE/fcm/service/FcmServiceImpl.java

fix : 헤드업 알림설정을 위한 Message 객체 변경

---

src/main/java/com/modagbul/BE/domain/user/controller/mypage/UserMyPageController.java
src/main/java/com/modagbul/BE/domain/user/dto/UserDto.java
src/main/java/com/modagbul/BE/domain/user/service/mypage/UserMyPageService.java
src/main/java/com/modagbul/BE/domain/user/service/mypage/UserMyPageServiceImpl.java

알림 설정에서 [전체 알림] 데이터가 없는것 같습니다! 에 대한 답변

fix : 전체 알림설정 api 추가

---

src/main/java/com/modagbul/BE/domain/mission/service/MissionService.java
src/main/java/com/modagbul/BE/domain/usermission/dto/UserMissionDetailDto.java

fix : missionDetail dueTo edit

---

src/main/java/com/modagbul/BE/domain/user/dto/UserDto.java
src/main/java/com/modagbul/BE/domain/user/service/mypage/UserMyPageServiceImpl.java

fix : mypage edit

---

src/main/java/com/modagbul/BE/domain/mission/dto/MissionListDto.java
src/main/java/com/modagbul/BE/domain/mission/repository/MissionRepository.java
src/main/java/com/modagbul/BE/domain/mission/service/MissionService.java

fix : mission list dueTo

---

src/main/java/com/modagbul/BE/domain/mission/service/MissionService.java

fix : dueTo date 계산

---

src/main/java/com/modagbul/BE/domain/team/repository/TeamRepositoryCustomImpl.java

fix: LocalDate수정

---

src/main/java/com/modagbul/BE/domain/team/repository/TeamRepositoryCustomImpl.java
src/main/java/com/modagbul/BE/domain/team_member/dto/TeamMemberDto.java
src/main/java/com/modagbul/BE/domain/team_member/service/TeamMemberServiceImpl.java

초대코드 인증 시 DTO 수정
초대코드 인증 시 DTO에 프로필 imageUrl 추가

fix: 초대코드 인증 시 DTO 수정
